### ISSUE TITLE
research specific disabilities and associated needs in the workplace. Assign suggestions and information for each specific need. Include in research.md file.

### ISSUE THREAD

**Issue by thaysom22** [thaysom22/SODA_hackathon_team_12#2]

**Comment by thaysom22** [comment]
we need to populate the google sheets with considerations and associated provisions - can anyone work on this today at all?

**Comment by VinBdev** [comment]
Hey Tom, I'll add all this into the research.md file shortly - if there is anything else just let me know :)

**Comment by thaysom22** [comment]
combined with #25
