### ISSUE TITLE
Add database items

### ISSUE THREAD

**Issue by seanyoung247** [thaysom22/SODA_hackathon_team_12#25]
Add disability Items to mongodb database

**Comment by seanyoung247** [comment]
Added data to ws_considerations and provisions from [spreadsheet](https://docs.google.com/spreadsheets/d/1Ue718UIFDrad98E6W4-87uTzHNbzUGutEetPi7uc1v0/edit#gid=0)

**Comment by thaysom22** [comment]
* updated information architecture of database
* added more provisions to database

**Comment by thaysom22** [comment]
@VinBdev has added to database but leaving this open for now
